CHAINMAIL_BOOTS:
  amount: 4
  type: IRON_INGOT
CHAINMAIL_CHESTPLATE:
  amount: 8
  type: IRON_INGOT
CHAINMAIL_HELMET:
  amount: 5
  type: IRON_INGOT
CHAINMAIL_LEGGINGS:
  amount: 7
  type: IRON_INGOT
DIAMOND_AXE:
  amount: 3
  type: DIAMOND
DIAMOND_BOOTS:
  amount: 4
  type: DIAMOND
DIAMOND_CHESTPLATE:
  amount: 8
  type: DIAMOND
DIAMOND_HELMET:
  amount: 5
  type: DIAMOND
DIAMOND_HOE:
  amount: 2
  type: DIAMOND
DIAMOND_LEGGINGS:
  amount: 7
  type: DIAMOND
DIAMOND_PICKAXE:
  amount: 3
  type: DIAMOND
DIAMOND_SPADE:
  amount: 1
  type: DIAMOND
DIAMOND_SWORD:
  amount: 2
  type: DIAMOND
GOLD_AXE:
  amount: 27
  type: GOLD_NUGGET
GOLD_BOOTS:
  amount: 36
  type: GOLD_NUGGET
GOLD_CHESTPLATE:
  amount: 8
  type: GOLD_INGOT
GOLD_HELMET:
  amount: 45
  type: GOLD_NUGGET
GOLD_HOE:
  amount: 18
  type: GOLD_NUGGET
GOLD_LEGGINGS:
  amount: 63
  type: GOLD_NUGGET
GOLD_PICKAXE:
  amount: 27
  type: GOLD_NUGGET
GOLD_SPADE:
  amount: 9
  type: GOLD_NUGGET
GOLD_SWORD:
  amount: 18
  type: GOLD_NUGGET
IRON_AXE:
  amount: 3
  type: IRON_INGOT
IRON_BOOTS:
  amount: 4
  type: IRON_INGOT
IRON_CHESTPLATE:
  amount: 8
  type: IRON_INGOT
IRON_HELMET:
  amount: 5
  type: IRON_INGOT
IRON_HOE:
  amount: 2
  type: IRON_INGOT
IRON_LEGGINGS:
  amount: 7
  type: IRON_INGOT
IRON_PICKAXE:
  amount: 3
  type: IRON_INGOT
IRON_SPADE:
  amount: 1
  type: IRON_INGOT
IRON_SWORD:
  amount: 2
  type: IRON_INGOT
SHEARS:
  amount: 2
  type: IRON_INGOT
STONE_AXE:
  amount: 3
  type: STONE
STONE_HOE:
  amount: 2
  type: STONE
STONE_PICKAXE:
  amount: 3
  type: STONE
STONE_SPADE:
  amount: 1
  type: STONE
STONE_SWORD:
  amount: 2
  type: STONE
